#!/bin/bash

#####
# A simple example of how a Python script can be used as part of a data pipeline.
#
# To use, open a terminal from the LVL2 directory and run
#       ./process_script < inputs.txt > outputs.txt
#####

while IFS=$'\n' read -r class gender age; do
  python3 predict.py $class $gender $age
done