#!/bin/bash

#####
# An example of using a Python script as a reusable component. Here it's used as
# part of a data pipeline where it takes input from one file and writes the output
# to another file.
#
# Open a terminal from the LVL2 directory and run
#       ./process_script < {space-delimited input file} > {output file}
#####

while IFS=$'\n' read -r class gender age; do
  python3 predict.py $class $gender $age
done